[package]
name = "z2p"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "=4.0.0-beta.9"
actix-http = "=3.0.0-beta.10"
serde = { version = "1", features = ["derive"]}

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
